# Generated by Django 5.0.4 on 2024-08-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotopiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profil_pic',
            field=models.FileField(blank=True, default='profilepic.png', null=True, upload_to='profilepic'),
        ),
    ]
